import { useState } from 'react'
import Head from 'next/head'

import Eres from './eres';
import RehabilitaciónVocal from './rehabilitacionVocal'
import EntrenaminetoVocal from './entrenamientoVocal';
import Checkout from './checkout';


export default function Home({ router }) {
  const [routing, _] = useState<any>({
    eres: <Eres />,
    rehabilitacionvocal: < RehabilitaciónVocal />,
    entrenamientovocal: <EntrenaminetoVocal />,
    checkout: <Checkout />
  });

  return (
    <>
      <Head>
        <title>Eres Voz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <>
        {routing[router as string]}
      </>
    </>
  )
}
