import { TranslateInterface } from '@/models/translate';

export const spanishTranslate: TranslateInterface = {
    categories:{
        Bronze: "Bronce",
        Silver: "Plata",
        Gold: "Oro",
        Black: "Negro",
    },
    hero: {
        heroText: "Auroras Collection.",
        heroSubText: "Auroras Collection como nuestra primera colección de NFTs, dará inicio a un apasionante viaje de crecimiento personal, social y colectivo. Inspirada en las Auroras Boreales, estas 777 obras  únicas hacen homenaje al arte y la sintonía.",
        heroSubText2: " Ser propietario de una Aurora, te permite acceder a asombrosos beneficios y ser reconocido como fundador de GO BEYOND!"
    },
    navbar: {
        categories: "Categorias",
        explore: "Explora",
        connect: "Conectar",
    },
    footer: {
        text1: "Embarquémonos en la creación de un nuevo mundo",
        support: "<strong>Soporte</strong>",
        faqs: "Preguntas Frecuentes",
        helpCenter: "Centro de ayuda",
        community: "<strong>Comunidad</strong>  ",
    },
    benefits: "Beneficios",
    seeMore: "Ver más",
    addToCart: "Añadir al carrito",
    exploreCollection: "Explorar colección",
    seeDetails: "Ver detalles",
    aboutTitle: "Auroras <span>Collection</span>",
    connectWallet: "Conectarme",
    disconnectWallet: "Desconectarme",
    price: "Precio",
    aboutText: "Auroras Collection como nuestra primera colección de NFTs, dará inicio a un apasionante viaje de crecimiento personal, social y colectivo. Inspirada en las Auroras Boreales, estas 777 obras  únicas hacen homenaje al arte y la sintonía. <br/><br/> Ser propietario de una <span>Aurora</span>, te permite acceder a asombrosos beneficios y ser reconocido como fundador de GO BEYOND!",
    details:{
        title: "Detalles",
    },
    register: {
        title: "Te damos la bienvenida a GoBeyond",
        subtitle: "Realiza el registro y entra al mundo de NTF’s de auroras boreales.",
        walletPlaceholder: "Dirección de wallet",
        emailPlaceholder: "Email",
        usernamePlaceholder: "Nombre de usuario",
        buttonText: "Registrarme",
        placeholderEmail: "Correo",
        placeholderName: "Nombre",
        placeholderLastName: "Apellido",
        placeholderPhone: "Número de whatsapp",
        message: "Este campo no admite espacios, para agregar nombres y apellidos separa los datos con un punto Ej: Jhon.Smith"
    },
    cart:{
        title: "Compra",
        inCart: "En el Carrito",
        modification: "Lo sentimos, recientemente hemos actualizado su carrito, por favor revíselo",
        checkout: "Pagar",
        total: "Total",
    },
    connect: {
        title: "Conecta tu wallet",
        subtitle: "Para continuar con el proceso de compra <br/> necesitas conectar tu wallet",
        cancel : "Cancelar",
        connect: "Conecta tu Wallet",
        create: "¿No tienes una wallet?",
        wc: "Escanea con walletConnect",
        mm: "Conecta con tu metamask Wallet",
        terms: "Al conectar tu wallet, acepta los terminos y condiciones",
        funds: "¿No tienes fondos? ",
    },
    congrats: {
        title: "Felicidades",
        subtitle: "Tu pago fue exitoso",
        text: "Puede revisar el hash de transacción en el siguiente enlace:",
        close: "Cerrar",
    },
    benefits1: {
        li1: "Tarjeta Débito",
        li2: "Acceso a cursos sobre el Metaverso",
        li3: "300 USD in Digital Assets",
        li4: "Acceso a White Listings",
    },
    benefits2: {
        li1: "Tarjeta Débito",
        li2: "Acceso a cursos sobre el Metaverso",
        li3: "1,000 USD en Activos Digitales",
        li4: "Acceso a White Listings",
    },
    benefits3: {
        li1: "Tarjeta Débito Black",
        li2: "Acceso a cursos sobre el Metaverso",
        li3: "5 Lotes de Landian",
        li4: "Rentabilidad de 5,000 USD al mes 12",
        li5: "3,000 USD en Activos Digitales",
        li6: "Acceso a White Listings",
        li7: "Entradas ilimitadas a conciertos de Landian durante un mes",
    },
    benefits4: {
        li1: "Tarjeta Débito Metálica",
        li2: "Acceso a cursos sobre el Metaverso",
        li3: "Acceso a Landian Headquarters",
        li4: "15 Lotes de Landian",
        li5: "Rentabilidad de 1,000 USD por 12 meses",
        li6: "1,000 Blumer Tokens",
        li7: "Cuenta verificada Blumer gratis",
        li8: "Acceso a todos los productos DEFI",
        li9: "5,000 USD en Activos Digitales",
        li10: "1 Personalized session about the Metaverse",
        li11: "Acceso a las White Listings",
        li12: "1 NFT APES BODY GUARD SQUAD",
        li13: "1 NFT FANTASMA DE LA NOCHE",
        li14: "Entradas ilimitadas a conciertos de",
        li15: "Landian por 6 Meses",
    },

    errors: {
        noUser: "Lo sentimos no hemos podido conseguir este usuario",
        register: "Usuario o correo invalido, por favor intente con otro.",
        noFunds: "Lo sentimos, el balance de tu cartera no es suficiente para comprar este NFT.",
    },
    notifications:{
        success: "NFT agregado",
    }
}